
config_1:
  closer_reward_factor: 0.5
  closer_reward_offset: 4
  collision_penalty: -5
  further_penalty_factor: 2.6
  further_penalty_offset: -5
  kill_penalty: -100
  remaining_step_reward_factor: 1.5
  still_penalty: -9
  win_reward: 500
config_2:
  closer_reward_factor: 0.25
  closer_reward_offset: 1
  collision_penalty: -1
  further_penalty_factor: 0.25
  further_penalty_offset: -1
  kill_penalty: -1000
  remaining_step_reward_factor: 2
  still_penalty: -1
  win_reward: 1000
config_3:
  closer_reward_factor: 0
  closer_reward_offset: -1
  collision_penalty: -1
  further_penalty_factor: 0
  further_penalty_offset: -1
  kill_penalty: -1000
  remaining_step_reward_factor: 0
  still_penalty: -1
  win_reward: 1000
config_4:
  closer_reward_factor: 0
  closer_reward_offset: -0.001
  collision_penalty: -0.003
  further_penalty_factor: 0
  further_penalty_offset: -0.001
  kill_penalty: -1
  remaining_step_reward_factor: 0
  still_penalty: -0.001
  win_reward: 1